//! Port traits defining the hexagonal architecture boundaries.
//!
//! Ports are pure interfaces. Implementations live in `gyre-adapters`.
//! Domain logic depends only on these traits, never on concrete adapters.

pub mod activity;
pub mod agent;
pub mod agent_tracking;
pub mod analytics;
pub mod attestation_repo;
pub mod audit;
pub mod budget;
pub mod budget_usage;
pub mod compute;
pub mod compute_target_repository;
pub mod container_audit_repo;
pub mod conversation;
pub mod dependency;
pub mod git_ops;
pub mod graph;
pub mod jj_ops;
pub mod kv_store;
pub mod llm;
pub mod llm_config;
pub mod merge_queue;
pub mod merge_request;
pub mod message;
pub mod meta_spec_repository;
pub mod meta_spec_set;
pub mod network;
pub mod notification;
pub mod policy;
pub mod pre_accept;
pub mod prompt_template;
pub mod push_gate;
pub mod quality_gate;
pub mod repository;
pub mod review;
pub mod saved_view;
pub mod search;
pub mod spawn_log;
pub mod spec_approval;
pub mod spec_approval_event_repo;
pub mod spec_ledger_repo;
pub mod spec_policy_repo;
pub mod storage;
pub mod task;
pub mod team;
pub mod tenant;
pub mod trace;
pub mod user;
pub mod user_profile;
pub mod user_workspace_state;
pub mod workspace;
pub mod workspace_membership;

pub use activity::{ActivityQuery, ActivityRepository};
pub use agent::AgentRepository;
pub use agent_tracking::{AgentCommitRepository, WorktreeRepository};
pub use analytics::{AnalyticsRepository, CostRepository};
pub use attestation_repo::AttestationRepository;
pub use audit::AuditRepository;
pub use budget::BudgetRepository;
pub use budget_usage::BudgetUsageRepository;
pub use compute::{ComputeTarget, ProcessHandle, SpawnConfig};
pub use compute_target_repository::ComputeTargetRepository;
pub use container_audit_repo::ContainerAuditRepository;
pub use conversation::ConversationRepository;
pub use dependency::DependencyRepository;
pub use git_ops::GitOpsPort;
pub use graph::GraphPort;
pub use jj_ops::{JjChange, JjOpsPort};
pub use kv_store::KvJsonStore;
pub use llm::{LlmPort, LlmPortFactory};
pub use llm_config::LlmConfigRepository;
pub use merge_queue::MergeQueueRepository;
pub use merge_request::MergeRequestRepository;
pub use message::{MessageConsumer, MessageRepository};
pub use meta_spec_repository::{MetaSpecBindingRepository, MetaSpecFilter, MetaSpecRepository};
pub use meta_spec_set::MetaSpecSetRepository;
pub use network::NetworkPeerRepository;
pub use notification::NotificationRepository;
pub use policy::PolicyRepository;
pub use pre_accept::{GateOutcome, PreAcceptGate, PushContext};
pub use prompt_template::PromptRepository;
pub use push_gate::PushGateRepository;
pub use quality_gate::{GateResultRepository, QualityGateRepository};
pub use repository::RepoRepository;
pub use review::ReviewRepository;
pub use saved_view::{SavedView, SavedViewRepository};
pub use search::{SearchDocument, SearchPort, SearchQuery, SearchResult};
pub use spawn_log::{SpawnLogEntry, SpawnLogRepository};
pub use spec_approval::SpecApprovalRepository;
pub use spec_approval_event_repo::SpecApprovalEventRepository;
pub use spec_ledger_repo::SpecLedgerRepository;
pub use spec_policy_repo::SpecPolicyRepository;
pub use storage::StoragePort;
pub use task::TaskRepository;
pub use team::TeamRepository;
pub use tenant::TenantRepository;
pub use trace::{SpanPayload, TraceRepository};
pub use user::{ApiKeyRepository, UserRepository};
pub use user_profile::{
    JudgmentLedgerRepository, UserNotificationPreferenceRepository, UserTokenRepository,
};
pub use user_workspace_state::UserWorkspaceStateRepository;
pub use workspace::{PersonaRepository, WorkspaceRepository};
pub use workspace_membership::WorkspaceMembershipRepository;
